### DISCUSSION TITLE
configuring ingress for dask-jupyter helm chart deployment

### DISCUSSION THREAD

**Discussion by b-weintraub** [dask/dask#8417] [Q&A]
I deployed a single-user dask-jupyter helm chart on a k8s cluster (https://github.com/dask/helm-chart/tree/main/dask).

$ helm ls

```
NAME  	NAMESPACE      	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
pangeo	wifire-quicfire	6       	2021-11-22 15:29:38.809774 -0800 PST	deployed	dask-2021.11.2	2021.11.2  
```
$ kubectl get svc pangeo-dask-jupyter pangeo-dask-scheduler

```
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
pangeo-dask-jupyter     ClusterIP   10.105.206.19   <none>        80/TCP            20h
pangeo-dask-scheduler   ClusterIP   10.107.121.88   <none>        8786/TCP,80/TCP   20h
```

I'm trying to expose an external ip.  My k8s does not allow the use of the LoadBalancer service so I'm trying to enable the ingress instead.

For exposing an external ip, I’m trying to enable ingress following this template:
https://github.com/dask/helm-chart/blob/main/dask/templates/dask-jupyter-ingress.yaml

Here’s the ingress part of my values.yaml:

```
  ingress:
    enabled: true  
    tls:   
      - hosts: 
        - wifire-commons-pangeo-jupyter.nrp-nautilus.io
        secretName: dask-jupyter-tls
    hostname: wifire-commons-pangeo-jupyter.nrp-nautilus.io  # Ingress hostname.
    annotations:  
      kubernetes.io/ingress.class: haproxy
```

When I run the update, here’s my error:
$ helm upgrade pangeo -f values.yaml dask/dask

Error: UPGRADE FAILED: YAML parse error on dask/templates/dask-jupyter-ingress.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context

Does anyone have any suggestions for configuring the YAML for ingress?
