### ISSUE TITLE
Are there any workarounds for dask breaking altogether with higher amounts of load than what fits into a worker

### ISSUE THREAD

**Issue by Cognitus-Stuti** [dask/dask#11396]
Are there any workarounds for dask breaking altogether with higher amounts of load than what fits into a worker.
Despite there being partitions the finalize step runs the entire thing on a single worker which renders the distributed mnature of things pointless here.
This causes the finalize step to fail in _apply_transformations is there any alternative to make sure the finalize step does not cause issues:

**Minimal Complete Verifiable Example**:

```python
import pandas as  pd
import dask.dataframe as dd
from contextlib import asynccontextmanager
from dask.distributed import Client
import dask
import asyncio
import os.path
class DaskClientContext:
    def __init__(self, client):
        self.client = client

    async def __aenter__(self):
        return self.client

    async def __aexit__(self, exc_type, exc_value, traceback):
        print("Exit Called")
        await self.client.close()


@asynccontextmanager
async def dask_client_context():
    async with Client("tcp://dask-scheduler:8786", asynchronous=True, direct_to_workers=True) as client:
        client.restart()
        
        yield client



async def _apply_transfromations(df):

    if not isinstance(df, dd.DataFrame):
        if isinstance(df, pd.DataFrame):
            dask_df = dd.from_pandas(df, npartitions=8)
    else:
        dask_df = df
    # try:
    async with dask_client_context() as client:
        try:
            dask.config.set(
                {
                    "distributed.workers.memory.spill": 0.80,
                    "distributed.workers.memory.target": 0.70,
                    "distributed.workers.memory.terminate": 0.99,
                    "optimization.fuse.ave-width": 4,
                    "dataframe.shuffle.method": "tasks",
                }
            )

            # dask_df = dask_df.persist()
            # result = client.c(dask_df)
            result = await client.compute(dask_df)

        except RuntimeError as e:
            raise ValueError(
                f"Error Applying Transformations for: {str(e)}"
            )
    
    return {"dataframe": result}

async def _concat_dask_dataframe(df_list):

    dask_list = []
    combined_meta = pd.DataFrame()
    n = 16
    for df in df_list:
        if not isinstance(df, dd.DataFrame):
            if isinstance(df, pd.DataFrame):
                npartitions = max(1, len(df) // 20_000)
                df = dd.from_pandas(df, npartitions=npartitions, sort=True)
            else:
                raise ValueError("All elements must be DataFrames")
        combined_meta_df_list = combined_meta_df_list.append(df._meta, ignore_index=True)
        
        dask_list.append(df)
    combined_meta = pd.concat(combined_meta_df_list, axis=0).iloc[0:0]
    combined_meta =dd.utils.make_meta(combined_meta.drop_duplicates(inplace=True))
    # print("n", n)

    data = dd.concat(dask_list,  meta=combined_meta).reset_index(
        drop=True
    )

    data=data.repartition(npartitions=n)
    return {"dataframe": data}


#feel free to use any csv with 50,000 rows

df = dd.read_csv("data.csv")
df = await _concat_dask_dataframe([df,df,df,df,df])
df = df["dataframe"]
df = await _concat_dask_dataframe([df,df,df,df,df])
df = df["dataframe"]

df = await _concat_dask_dataframe([df,df,df,df,df])
df = df["dataframe"]

df = await _apply_transfromations(df)
df = df["dataframe"]
```

I do have limited compute here this is the docker compose 
```
dask-scheduler:
    image: ghcr.io/dask/dask:2024.5.2-py3.12
    ports:
      - "8786:8786"
      - "8787:8787"
    command:
      - bash
      - -c
      - |
        pip install requests aiohttp
        dask-scheduler
    environment:
      - PYTHONWARNINGS=ignore
    networks:
      - dask
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /data:/data
      - ./etc/dask:/etc/dask
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "3G"
        reservations:
          cpus: "2"
          memory: "3G"
    restart: always

  dask-worker:
    image: ghcr.io/dask/dask:2024.5.2-py3.12
    environment:
      - DASK_CONFIG=/etc/dask
      - PYTHONWARNINGS=ignore

    volumes:
      - ./etc/dask:/etc/dask
      - ./tmp/dask-worker-space:/tmp/dask-worker-space
      - ./data:/data
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2.0"
          memory: "3G"
        reservations:
          cpus: "2.0"
          memory: "3G"
    command:
      - bash
      - -c
      - |
        pip install requests aiohttp
        dask worker dask-scheduler:8786 
    networks:
      - dask
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
networks:
  dask:
    driver: bridge
  default:
    external:
      name: host
```

**Environment**:

- Dask version:2024.5.2
- Python version:3.12
- Operating System:Ubuntu 22.04
- Install method (conda, pip, source):pip
