### ISSUE TITLE
Trouble computing with `h5py`-based Dask Arrays 

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#1777]
Below I attempt to compute something using an `h5py.Dataset`. To confirm that it isn't some other issue like data size, chunking, etc., I compute the same thing with a `numpy.ndarray`. In both cases, I am using IPyParallel to start up the cluster and let `distribute` hook in. Re-ordering the two steps has no effect on the outcome. However, as this is pretty new to me I may have missed some subtle nuances about how this should be done. 😄

```python
In [1]: import ipyparallel as ipy

In [2]: import dask.array as da

In [3]: import numpy as np

In [4]: import h5py as hp

In [5]: a = np.random.random((10, 11, 12))

In [6]: with hp.File("dask.h5", "w") as f:
   ...:     f.create_dataset("data", data=a, chunks=True)
   ...:     

In [7]: f = hp.File("dask.h5", "r")

In [8]: b1 = da.from_array(a, chunks=f["data"].chunks)

In [9]: b2 = da.from_array(f["data"], chunks=f["data"].chunks)

In [10]: c = ipy.Client()

In [11]: dc = c.become_distributed()

In [12]: dc.compute(b1.mean(axis=0)).result()
Out[12]: 
array([[ 0.65777228,  0.46362167,  0.56978135,  0.50914932,  0.64354382,
         0.45940105,  0.51149941,  0.52684094,  0.58892004,  0.36324491,
         0.51609531,  0.47163727],
       [ 0.58730589,  0.43109694,  0.40044725,  0.57055902,  0.4251899 ,
         0.53296484,  0.54781415,  0.57013316,  0.43522948,  0.49956828,
         0.48640079,  0.48295392],
       [ 0.55618845,  0.49037593,  0.55877852,  0.64472259,  0.43578943,
         0.54305746,  0.54831807,  0.32826133,  0.53886436,  0.60186004,
         0.40533537,  0.55482734],
       [ 0.5026686 ,  0.39912454,  0.46250177,  0.49297201,  0.64641005,
         0.599465  ,  0.50289519,  0.45107388,  0.48660165,  0.47501224,
         0.68269245,  0.44125048],
       [ 0.37777522,  0.39422423,  0.34592339,  0.45493433,  0.66028808,
         0.55596105,  0.54033778,  0.36616862,  0.54607348,  0.39671224,
         0.45072439,  0.5041624 ],
       [ 0.6185854 ,  0.68881169,  0.44188108,  0.43924929,  0.57976752,
         0.52912726,  0.27132828,  0.5113303 ,  0.4562832 ,  0.65787405,
         0.52372686,  0.44670093],
       [ 0.67536224,  0.4269958 ,  0.50525186,  0.36806941,  0.36638702,
         0.52503383,  0.54293096,  0.44907095,  0.56952067,  0.3554773 ,
         0.59716953,  0.46010925],
       [ 0.58255168,  0.45300169,  0.46838193,  0.41620449,  0.32193123,
         0.52798741,  0.61645301,  0.3636535 ,  0.55636865,  0.54486539,
         0.41816519,  0.49918014],
       [ 0.41691407,  0.63624961,  0.55867685,  0.49339445,  0.54604918,
         0.32999289,  0.44992597,  0.48196588,  0.49291533,  0.35763387,
         0.40635266,  0.52340777],
       [ 0.61846875,  0.61683379,  0.50748862,  0.37104707,  0.52841106,
         0.47472112,  0.60518365,  0.53413459,  0.37561132,  0.32097623,
         0.58674229,  0.38897782],
       [ 0.45351179,  0.47328419,  0.53388495,  0.47578736,  0.52435889,
         0.43159956,  0.52070268,  0.56110094,  0.68299126,  0.55215202,
         0.55655897,  0.49930457]])

In [13]: dc.compute(b2.mean(axis=0)).result()
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-13-ac96b99dab60> in <module>()
----> 1 dc.compute(b2.mean(axis=0)).result()

/zopt/conda2/envs/daskenv/lib/python2.7/site-packages/distributed/client.pyc in result(self)
    108         result = sync(self.client.loop, self._result, raiseit=False)
    109         if self.status == 'error':
--> 110             six.reraise(*result)
    111         if self.status == 'cancelled':
    112             raise result

/zopt/conda2/envs/daskenv/lib/python2.7/site-packages/six.pyc in reraise(tp, value, tb)

KilledWorker: ("('mean_agg-aggregate-c38bdc894005501a402f66836cbb8da7', 0, 0)", '10.8.1.99:60536')
```

How the cluster was started.

```bash
$ ipcluster start -n 4
2016-11-11 16:35:04.056 [IPClusterStart] Starting ipcluster with [daemon=False]
2016-11-11 16:35:04.056 [IPClusterStart] Creating pid file: /Users/kirkhamj/.ipython/profile_default/pid/ipcluster.pid
2016-11-11 16:35:04.057 [IPClusterStart] Starting Controller with LocalControllerLauncher
2016-11-11 16:35:05.062 [IPClusterStart] Starting 4 Engines with LocalEngineSetLauncher
2016-11-11 16:35:35.395 [IPClusterStart] Engines appear to have started successfully
```

ipyparallel configuration file `ipcluster_config.py`. `CORES` was undefined in this case so `n` is `1`.

```python
import os


c = get_config()

c.IPClusterEngines.n = int(os.environ.get("CORES", 2)) - 1

c.HubFactory.ip = '*'
c.HubFactory.engine_ip = '*'
c.HubFactory.db_class = "SQLiteDB"

c.IPEngineApp.wait_for_url_file = 60
c.EngineFactory.timeout = 60
```

Environment used to run `dask`/`distribute`.

```yaml
name: daskenv
channels:
- nanshe
- jakirkham
- conda-forge
- defaults
- javascript
dependencies:
- appnope=0.1.0=py27_0
- bokeh=0.12.3=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_0
- conda-forge::backports_abc=0.4=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::boto3=1.4.1=py27_0
- conda-forge::botocore=1.4.49=py27_0
- conda-forge::ca-certificates=2016.9.26=0
- conda-forge::certifi=2016.9.26=py27_0
- conda-forge::click=6.6=py27_1
- conda-forge::cloudpickle=0.2.1=py27_2
- conda-forge::configparser=3.5.0=py27_0
- conda-forge::dask=0.12.0=py27_0
- conda-forge::decorator=4.0.10=py27_0
- conda-forge::docutils=0.12=py27_0
- conda-forge::entrypoints=0.2.2=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::h5py=2.6.0=np111py27_6
- conda-forge::hdf5=1.8.17=7
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::ipykernel=4.5.0=py27_0
- conda-forge::ipyparallel=5.2.0=py27_1
- conda-forge::ipython=5.1.0=py27_1
- conda-forge::ipython_genutils=0.1.0=py27_0
- conda-forge::jinja2=2.8=py27_1
- conda-forge::jmespath=0.9.0=py27_0
- conda-forge::jsonschema=2.5.1=py27_0
- conda-forge::jupyter_client=4.4.0=py27_0
- conda-forge::jupyter_core=4.2.0=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::locket=0.2.0=py27_1
- conda-forge::markupsafe=0.23=py27_0
- conda-forge::mistune=0.7.3=py27_0
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::nbconvert=4.2.0=py27_0
- conda-forge::nbformat=4.1.0=py27_0
- conda-forge::ncurses=5.9=9
- conda-forge::notebook=4.2.3=py27_0
- conda-forge::numpy=1.11.2=py27_blas_openblas_200
- conda-forge::openblas=0.2.18=6
- conda-forge::openssl=1.0.2h=2
- conda-forge::pandas=0.19.1=np111py27_0
- conda-forge::partd=0.3.6=py27_0
- conda-forge::pathlib2=2.1.0=py27_0
- conda-forge::pexpect=4.2.0=py27_1
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.9=py27_0
- conda-forge::psutil=4.3.0=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.1.3=py27_1
- conda-forge::python=2.7.12=1
- conda-forge::python-dateutil=2.5.3=py27_0
- conda-forge::pytz=2016.7=py27_0
- conda-forge::pyyaml=3.11=py27_0
- conda-forge::pyzmq=16.0.0=py27_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.11.1=py27_0
- conda-forge::s3fs=0.0.7=py27_0
- conda-forge::s3transfer=0.1.8=py27_0
- conda-forge::setuptools=28.8.0=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_0
- conda-forge::terminado=0.6=py27_0
- conda-forge::tk=8.5.19=0
- conda-forge::toolz=0.8.0=py27_0
- conda-forge::tornado=4.4.2=py27_0
- conda-forge::traitlets=4.3.1=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zict=0.1.0=py27_0
- conda-forge::zlib=1.2.8=3
- nanshe::distributed=1.14.2=py27_0
- python.app=1.2=py27_4
- tblib=1.3.0=py27_0
prefix: /zopt/conda2/envs/daskenv
```
