### ISSUE TITLE
__setitem__ results in shape change

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2005]
I'm running into an issue with `__setitem__` currently where it seems to result in a shape change to the array that it is assigned to. An example with workarounds in comments is shown below in the (folded) details. Also included info about my environment is included.

Though it is unclear to me in what sense this is a bug. Am I doing something that is unsupported? Maybe we need to be raising an exception then. Also is the bug actually with `__setitem__` or is it some graph structuring/optimization issue?

Example:

<details>
<br>
Code:

```python
i = da.from_array(np.array(120*[5]).reshape(10,12), chunks=(5,6,))
a = da.zeros((10, 12), dtype=int, chunks=(5,6))

# Workaround 1 (comment other `b` stuff below and uncomment this)
# b = da.from_array(np.array(12*[[True] + (10-1)*[False]]).T.copy(), chunks=(5, 6))

b = da.from_array(np.array([True] + (10-1)*[False]), chunks=(5,))
b = da.stack(12*[b], axis=-1)
# Workaround 2
#b = b.rechunk((5,6))

print(a.shape)
print(b.shape)
print(i.shape)
# Workaround 3
#print(a.compute())

a[b] = i

print(a.compute().shape)
print(a.compute())
```

Output:

```
(10, 12)
(10, 12)
(10, 12)
(10, 2)
[[5 5]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
```

</details>

<br>
Environment details:
<br>
<br>

<details>

```yaml
name: root
channels: !!python/tuple
- !!python/unicode
  'nanshe'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- apr=1.5.2=1
- beautifulsoup4=4.5.3=py27_0
- bokeh=0.12.4=py27_0
- bzip2=1.0.6=3
- conda-forge::anaconda-client=1.5.1=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::bleach=1.5.0=py27_0
- conda-forge::boost=1.63.0=np111py27_6
- conda-forge::boost-cpp=1.63.0=2
- conda-forge::boto3=1.4.2=py27_0
- conda-forge::botocore=1.4.81=py27_0
- conda-forge::bottleneck=1.2.0=np111py27_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::cairo=1.14.6=4
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::cffi=1.7.0=py27_0
- conda-forge::chardet=2.3.0=py27_0
- conda-forge::click=6.7=py27_0
- conda-forge::cloudpickle=0.2.2=py27_2
- conda-forge::clyent=1.2.1=py27_0
- conda-forge::conda=4.2.16=py27_0
- conda-forge::conda-build=2.1.4=py27_0
- conda-forge::conda-env=2.6.0=0
- conda-forge::configparser=3.5.0=py27_0
- conda-forge::contextlib2=0.5.4=py27_0
- conda-forge::curl=7.52.1=0
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::dask=0.13.0=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::distributed=1.15.2=py27_0
- conda-forge::docutils=0.13.1=py27_0
- conda-forge::entrypoints=0.2.2=py27_1
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::expat=2.1.0=2
- conda-forge::fasteners=0.14.1=py27_2
- conda-forge::fftw=3.3.6=0
- conda-forge::filelock=2.0.6=py27_0
- conda-forge::fontconfig=2.12.1=4
- conda-forge::freetype=2.7=1
- conda-forge::funcsigs=1.0.2=py27_0
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::future=0.16.0=py27_0
- conda-forge::futures=3.0.5=py27_0
- conda-forge::gettext=0.19.7=1
- conda-forge::git=2.8.2=4
- conda-forge::glib=2.51.0=2
- conda-forge::gmp=6.1.2=0
- conda-forge::h5py=2.6.0=np111py27_7
- conda-forge::harfbuzz=1.3.4=2
- conda-forge::hdf5=1.8.17=9
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::icu=58.1=1
- conda-forge::idna=2.1=py27_0
- conda-forge::imgroi=0.0.1=py27_0
- conda-forge::ipaddress=1.0.16=py27_0
- conda-forge::ipykernel=4.5.2=py27_0
- conda-forge::ipyparallel=6.0.0=py27_0
- conda-forge::ipython=5.2.2=py27_0
- conda-forge::ipython_genutils=0.1.0=py27_0
- conda-forge::ipywidgets=5.2.2=py27_2
- conda-forge::jinja2=2.8=py27_1
- conda-forge::jmespath=0.9.1=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::jsonschema=2.5.1=py27_0
- conda-forge::jupyter_client=4.4.0=py27_0
- conda-forge::jupyter_core=4.2.1=py27_0
- conda-forge::kenjutsu=0.4.0=py27_0
- conda-forge::libffi=3.2.1=3
- conda-forge::libiconv=1.14=4
- conda-forge::libpng=1.6.28=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::libxml2=2.9.4=4
- conda-forge::locket=0.2.0=py27_1
- conda-forge::mahotas=1.4.3=np111py27_1
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::matplotlib=2.0.0=np111py27_2
- conda-forge::mercurial=4.1=py27_1
- conda-forge::metawrap=0.0.1=py27_0
- conda-forge::mistune=0.7.3=py27_1
- conda-forge::mock=2.0.0=py27_0
- conda-forge::monotonic=1.2=py27_1
- conda-forge::mplview=0.0.1=py27_0
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::nbconvert=5.1.1=py27_0
- conda-forge::nbformat=4.2.0=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::networkx=1.11=py27_0
- conda-forge::notebook=4.4.1=py27_0
- conda-forge::npctypes=0.0.2=py27_0
- conda-forge::numpy=1.11.3=py27_blas_openblas_200
- conda-forge::olefile=0.44=py27_0
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.2=np111py27_1
- conda-forge::pandoc=1.19.2=0
- conda-forge::pandocfilters=1.4.1=py27_0
- conda-forge::pango=1.40.3=3
- conda-forge::partd=0.3.7=py27_0
- conda-forge::patchelf=0.9=1
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pbr=1.10.0=py27_0
- conda-forge::pcre=8.39=0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pillow=4.0.0=py27_2
- conda-forge::pip=9.0.1=py27_0
- conda-forge::pixman=0.34.0=0
- conda-forge::pkginfo=1.2.1=py27_0
- conda-forge::prompt_toolkit=1.0.13=py27_0
- conda-forge::psutil=5.1.3=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pyasn1=0.1.9=py27_0
- conda-forge::pycosat=0.6.1=py27_0
- conda-forge::pycparser=2.17=py27_0
- conda-forge::pycrypto=2.6.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyparsing=2.1.10=py27_0
- conda-forge::pyqt=4.11.4=py27_2
- conda-forge::python=2.7.12=2
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::pytz=2016.10=py27_0
- conda-forge::pyyaml=3.12=py27_0
- conda-forge::pyzmq=16.0.2=py27_1
- conda-forge::qt=4.8.7=7
- conda-forge::rank_filter=0.4.12=np111py27_2
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::ruamel_yaml=0.11.14=py27_0
- conda-forge::runipy=0.1.5=py27_0
- conda-forge::s3fs=0.0.9=py27_0
- conda-forge::s3transfer=0.1.9=py27_0
- conda-forge::scandir=1.3=py27_1
- conda-forge::scikit-image=0.12.3=np111py27_0
- conda-forge::scikit-learn=0.18=np111py27_blas_openblas_203
- conda-forge::scipy=0.18.1=np111py27_blas_openblas_201
- conda-forge::setuptools=33.1.0=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::sip=4.18=py27_1
- conda-forge::six=1.10.0=py27_1
- conda-forge::sortedcontainers=1.5.3=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_0
- conda-forge::subprocess32=3.2.7=py27_0
- conda-forge::terminado=0.6=py27_0
- conda-forge::testpath=0.3=py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::toolz=0.8.2=py27_0
- conda-forge::tornado=4.4.2=py27_0
- conda-forge::traitlets=4.3.1=py27_0
- conda-forge::vigra=1.11.0=np111py27_11
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::webcolors=1.5=py27_2
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::widgetsnbextension=1.2.6=py27_3
- conda-forge::xnumpy=0.1.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::yail=0.0.1=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.2.1=1
- conda-forge::zict=0.1.1=py27_0
- conda-forge::zlib=1.2.11=0
- conda-verify=2.0.0=py27_0
- cryptography=1.7.1=py27_0
- drmaa=0.7.6=py27_0
- html5lib=0.999=py27_0
- libgfortran=3.0.0=1
- nanshe::nanshe=0.1.0a56=py27_0
- nanshe::zarr=2.1.4.dev12=py27_0
- pyopenssl=16.2.0=py27_0
- serf=1.3.8=1
- svn=1.9.4=0
- tblib=1.3.0=py27_0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.1
  - nanshe-workflow (/nanshe_workflow)==2.0.1
  - prompt-toolkit==1.0.13
  - rank-filter==0.4.12
  - ruamel-yaml==0.11.14
prefix: /opt/conda2
```

</details>
