### ISSUE TITLE
Unable to use map_overlap with a trivial depth

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2258]
It seems that if we specify `map_overlap` to have a trivial `depth` (i.e. zero), that we are unable to compute the result. Instead would have expected this trivial case to reduce to `map_blocks` potentially with some additional exercise of adding and removing a non-existent halo.

Edit: Interestingly this doesn't seem to be specific to occur for any depth with a `0` in it. As there appears to be one case here where it succeeds. 😕 So would conclude this is not intentional behavior, but some kind of bug.

Traceback:

<details>

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: a = np.arange(140.0).reshape(10, 14)

In [4]: d = da.from_array(a, chunks=(5, 7))

In [5]: d2 = d.map_overlap(lambda i: i, depth=(0, 0), boundary="none", dtype=d.dtype)

In [6]: d2.compute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-1446f707f21e> in <module>()
----> 1 d2.compute()

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
     93             Extra keywords to forward to the scheduler ``get`` function.
     94         """
---> 95         (result,) = compute(self, traverse=False, **kwargs)
     96         return result
     97 

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
    205     return tuple(a if not isinstance(a, Base)
    206                  else a._finalize(next(results_iter))
--> 207                  for a in args)
    208 
    209 

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/base.pyc in <genexpr>((a,))
    205     return tuple(a if not isinstance(a, Base)
    206                  else a._finalize(next(results_iter))
--> 207                  for a in args)
    208 
    209 

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/array/core.pyc in finalize(results)
    914     while isinstance(results2, (tuple, list)):
    915         if len(results2) > 1:
--> 916             return concatenate3(results)
    917         else:
    918             results2 = results2[0]

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/array/core.pyc in concatenate3(arrays)
   3350             while arr.ndim < ndim:
   3351                 arr = arr[None, ...]
-> 3352         result[idx] = arr
   3353 
   3354     return result

ValueError: could not broadcast input array from shape (0,7) into shape (5,7)

In [7]: d2 = d.map_overlap(lambda i: i, depth=(0, 1), boundary="none", dtype=d.dtype)

In [8]: d2.compute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-1446f707f21e> in <module>()
----> 1 d2.compute()

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
     93             Extra keywords to forward to the scheduler ``get`` function.
     94         """
---> 95         (result,) = compute(self, traverse=False, **kwargs)
     96         return result
     97 

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
    200     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    201     keys = [var._keys() for var in variables]
--> 202     results = get(dsk, keys, **kwargs)
    203 
    204     results_iter = iter(results)

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    498                     _execute_task(task, data)  # Re-execute locally
    499                 else:
--> 500                     raise(remote_exception(res, tb))
    501             state['cache'][key] = res
    502             finish_task(dsk, key, state, results, keyorder.get)

ValueError: could not broadcast input array from shape (0,8) into shape (5,8)

Traceback
---------
  File "/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/async.py", line 246, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)
  File "/zopt/conda2/envs/test/lib/python2.7/site-packages/dask/array/core.py", line 3352, in concatenate3
    result[idx] = arr


In [9]: d2 = d.map_overlap(lambda i: i, depth=(1, 0), boundary="none", dtype=d.dtype)

In [10]: d2.compute()
Out[10]: 
array([[   0.,    1.,    2.,    3.,    4.,    5.,    6.],
       [  14.,   15.,   16.,   17.,   18.,   19.,   20.],
       [  28.,   29.,   30.,   31.,   32.,   33.,   34.],
       [  42.,   43.,   44.,   45.,   46.,   47.,   48.],
       [  56.,   57.,   58.,   59.,   60.,   61.,   62.],
       [  70.,   71.,   72.,   73.,   74.,   75.,   76.],
       [  84.,   85.,   86.,   87.,   88.,   89.,   90.],
       [  98.,   99.,  100.,  101.,  102.,  103.,  104.],
       [ 112.,  113.,  114.,  115.,  116.,  117.,  118.],
       [ 126.,  127.,  128.,  129.,  130.,  131.,  132.]])
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: test
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::bokeh=0.12.5=py27_0
- conda-forge::boto3=1.4.4=py27_0
- conda-forge::botocore=1.5.39=py27_0
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::click=6.7=py27_0
- conda-forge::cloudpickle=0.2.2=py27_2
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::dask=0.14.1=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::distributed=1.16.1=py27_0
- conda-forge::docutils=0.13.1=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::freetype=2.7=1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jmespath=0.9.2=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::locket=0.2.0=py27_1
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::matplotlib=2.0.0=np112py27_3
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pandas=0.19.2=np112py27_1
- conda-forge::partd=0.3.7=py27_0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::psutil=5.2.1=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyparsing=2.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::pytz=2017.2=py27_0
- conda-forge::pyyaml=3.12=py27_1
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::s3fs=0.0.9=py27_0
- conda-forge::s3transfer=0.1.10=py27_1
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sortedcontainers=1.5.3=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_1
- conda-forge::subprocess32=3.2.7=py27_0
- conda-forge::tblib=1.3.2=py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::toolz=0.8.2=py27_0
- conda-forge::tornado=4.5.1=py27_0
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zict=0.1.1=py27_0
- conda-forge::zlib=1.2.11=0
```

</details>
