### ISSUE TITLE
utility to expand environment variables in dask config

### ISSUE THREAD

**Issue by jhamman** [dask/dask#3879]
It would be useful if dask could (optionally) expand environment variables in its config module. This may not always be useful but @mrocklin and I ran into a case today where it is the logical solution. Consider the following dask configuration file.

```yaml
# dask config file...
kubernetes:
  worker-template:
    metadata:
    spec:
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-worker
```

Origianally, I had intended to set the image variable by setting  `${DASK_KUBERNETES__WORKER_TEMPLATE__SPEC__IMAGE}`. However, in this case, `containers` is a list and the current environment variable approach is not able to handle indexing in the 0th position of the list. A simple python snippit like this does the required indexing but is clearly not general enough to be useful beyond my immediate application:

```Python
dask.config.config['kubernetes']['worker-template']['spec']['containers'][0]['image'] = os.environ['JUPYTER_IMAGE_SPEC']
```

------

At the moment, this feature seems most useful to dask-kubernetes. I know we don't want to expand environment variables in dask-jobqueue. So this seems like something that we would want to users/downstream packages to be able to opt into. I'm thinking a utility in `dask.config` to optionally expand environment variables would useful.
