### ISSUE TITLE
I failed to use .config/dask/dask.yaml set logger,why?

### ISSUE THREAD

**Issue by tarjintor** [dask/dask#5126]
I am using dask==1.2.2,distributed==1.28.1
I wish to change my worker's logger configs,like format
I read https://docs.dask.org/en/latest/configuration.html
and change my dask.yaml to

```
logging:
  distributed: debug
  bokeh: critical
  tornado: critical

scheduler:
  work-stealing: True
  allowed-failures: 5

admin:
  log-format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
```
but my logger level did not change, nor the format of logging message.
My guess is admin.log-format do not mean the distributed worker logger format, but I can't find a doc about the detail of the configurations
what can I do?

=========================================

I guess it's because the configuration is on scheduler's node not on worker's node, so I should pass env to worker when I instantiate the worker.
I set env,but I don't know the rule, so I use the example to guess,but still failed!
```
echo $ADMIN__LOG_FORMAT
%(asctime)s - %(name)s - %(levelname)s - %(message)s
echo $LOGGING__DISTRIBUTED
10
```
10 is logging.DEBUG

===============================
I read source code and find the logic in dask/config.py
If you set 

```
env = {'DASK_DISTRIBUTED__ADMIN__LOG_FORMAT': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
      'DASK__LOGGING__DISTRIBUTED': logging.DEBUG}
```
you will get what you want

====================================

But I still want a doc of all configurations together,rather than read the source code
