### ISSUE TITLE
ModuleNotFoundError: No module named 'numba'

### ISSUE THREAD

**Issue by JK87iab** [dask/dask#5817]
Hi,
can't execute numba code via map_blocks()

Installed dask on azure kubernetes and the normal examples all work fine.

Minimal test code
```
from dask.distributed import Client, progress
c = Client()
c

import numba
import dask.array as da
import numpy as np

@jit(nopython=True)
def array_1(x):
    x[:,1] = np.exp(x[:,2] * x[:,4])
    
    return x

x_np = np.random.random(size=(10000, 10000))

x_dask = da.from_array(x_np, chunks=(1000, 1000))

y = x_dask.map_blocks(array_1, dtype='float64')
y.compute()

```

results in 

`ModuleNotFoundError: No module named 'numba'`

config.yaml

```
worker:
  replicas: 8
  resources:
    limits:
      cpu: 2
      memory: 7.5G
    requests:
      cpu: 2
      memory: 7.5G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: s3fs dask-ml --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: s3fs dask-ml --upgrade
```

Is there a way to verify if numba is correctly installed on workers?
