### ISSUE TITLE
Xgboost on K8s does not work

### ISSUE THREAD

**Issue by danielhstahl** [dask/dask#8315]
**What happened**:

I get the following error when running XGBoost on Kubernetes:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_62/3178767199.py in <module>
      7 dtrain = xgb.dask.DaskDMatrix(client, X, y)
      8 
----> 9 output = xgb.dask.train(
     10     client,
     11     {"verbosity": 2, "tree_method": "hist", "objective": "reg:squarederror"},

/opt/conda/lib/python3.8/site-packages/xgboost/dask.py in train(client, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, xgb_model, verbose_eval, callbacks)
    979     client = _xgb_get_client(client)
    980     args = locals()
--> 981     return client.sync(_train_async, global_config=config.get_config(), **args)
    982 
    983 

/opt/conda/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    863             return future
    864         else:
--> 865             return sync(
    866                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    867             )

/opt/conda/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    325     if error[0]:
    326         typ, exc, tb = error[0]
--> 327         raise exc.with_traceback(tb)
    328     else:
    329         return result[0]

/opt/conda/lib/python3.8/site-packages/distributed/utils.py in f()
    308             if callback_timeout is not None:
    309                 future = asyncio.wait_for(future, callback_timeout)
--> 310             result[0] = yield future
    311         except Exception:
    312             error[0] = sys.exc_info()

/opt/conda/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

/opt/conda/lib/python3.8/site-packages/xgboost/dask.py in _train_async(client, global_config, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, verbose_eval, xgb_model, callbacks)
    845 ) -> Optional[TrainReturnT]:
    846     workers = _get_workers_from_data(dtrain, evals)
--> 847     _rabit_args = await _get_rabit_args(len(workers), client)
    848 
    849     if params.get("booster", None) == "gblinear":

/opt/conda/lib/python3.8/site-packages/xgboost/dask.py in _get_rabit_args(n_workers, client)
    803 async def _get_rabit_args(n_workers: int, client: "distributed.Client") -> List[bytes]:
    804     '''Get rabit context arguments from data distribution in DaskDMatrix.'''
--> 805     env = await client.run_on_scheduler(_start_tracker, n_workers)
    806     rabit_args = [f"{k}={v}".encode() for k, v in env.items()]
    807     return rabit_args

/opt/conda/lib/python3.8/site-packages/distributed/client.py in _run_on_scheduler(self, function, wait, *args, **kwargs)
   2366 
   2367     async def _run_on_scheduler(self, function, *args, wait=True, **kwargs):
-> 2368         response = await self.scheduler.run_function(
   2369             function=dumps(function, protocol=4),
   2370             args=dumps(args, protocol=4),

/opt/conda/lib/python3.8/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    861             name, comm.name = comm.name, "ConnectionPool." + key
    862             try:
--> 863                 result = await send_recv(comm=comm, op=key, **kwargs)
    864             finally:
    865                 self.pool.reuse(self.addr, comm)

/opt/conda/lib/python3.8/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    654         if comm.deserialize:
    655             typ, exc, tb = clean_exception(**response)
--> 656             raise exc.with_traceback(tb)
    657         else:
    658             raise Exception(response["exception_text"])

/opt/conda/lib/python3.8/site-packages/distributed/core.py in handle_comm()
    496                             result = asyncio.ensure_future(result)
    497                             self._ongoing_coroutines.add(result)
--> 498                             result = await result
    499                     except (CommClosedError, CancelledError):
    500                         if self.status in (Status.running, Status.paused):

/opt/conda/lib/python3.8/site-packages/distributed/worker.py in run()
   4352 async def run(server, comm, function, args=(), kwargs=None, is_coro=None, wait=True):
   4353     kwargs = kwargs or {}
-> 4354     function = pickle.loads(function)
   4355     if is_coro is None:
   4356         is_coro = iscoroutinefunction(function)

/opt/conda/lib/python3.8/site-packages/distributed/protocol/pickle.py in loads()
     73             return pickle.loads(x, buffers=buffers)
     74         else:
---> 75             return pickle.loads(x)
     76     except Exception:
     77         logger.info("Failed to deserialize %s", x[:10000], exc_info=True)

ModuleNotFoundError: No module named 'xgboost'

**What you expected to happen**:

I expected xgboost to train.  I am able to train xgboost with no issues using LocalCluster.

**Minimal Complete Verifiable Example**:

I installed dask on minikube as described here: https://docs.dask.org/en/latest/how-to/deploy-dask/kubernetes-helm.html

I am able to run all the examples in the notebook.  

I added xgboost to the workers and the notebook using the following yaml:
```yaml
worker:
  replicas: 2
  resources:
    limits:
      cpu: 2
      memory: 1G
    requests:
      cpu: 2
      memory: 1G
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: xgboost -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml --upgrade
```

I then run this code in a notebook cell:
```python
import xgboost as xgb
import dask.array as da
from dask.distributed import Client

client = Client()

# X and y must be Dask dataframes or arrays
num_obs = 1e5
num_features = 20
X = da.random.random(size=(num_obs, num_features), chunks=(1000, num_features))
y = da.random.random(size=(num_obs, 1), chunks=(1000, 1))

dtrain = xgb.dask.DaskDMatrix(client, X, y)

output = xgb.dask.train(
    client,
    {"verbosity": 2, "tree_method": "hist", "objective": "reg:squarederror"},
    dtrain,
    num_boost_round=4,
    evals=[(dtrain, "train")],
)
```

It errors during xgb.dask.train.

**Anything else we need to know?**:
When I exec into each worker pod I'm able to import xgboost; so its clearly been installed on all the workers.
**Environment**:

- Dask version: '2021.10.0'
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): Kubernetes (Helm)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @danielhstahl. The `ModuleNotFoundError: No module named 'xgboost'` error indicates that `xgboost` isn't installed on the cluster workers. Maybe the workers are using a different Python environment than the one you exec'ed into? Can you inspect the output of `client.get_versions(packages=["xgboost"], check=True)` to make sure the same version of `xgboost` is installed on all nodes of your cluster?

**Comment by danielhstahl** [comment]
Nothing seems off about it:
```
{'scheduler': {'host': {'python': '3.8.12.final.0',
   'python-bits': 64,
   'OS': 'Linux',
   'OS-release': '5.13.0-20-generic',
   'machine': 'x86_64',
   'processor': 'x86_64',
   'byteorder': 'little',
   'LC_ALL': 'C.UTF-8',
   'LANG': 'C.UTF-8'},
  'packages': {'python': '3.8.12.final.0',
   'dask': '2021.10.0',
   'distributed': '2021.10.0',
   'msgpack': '1.0.2',
   'cloudpickle': '2.0.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.21.1',
   'pandas': '1.3.0',
   'lz4': '3.1.3',
   'blosc': '1.10.2',
   'xgboost': None}},
 'workers': {'tcp://172.17.0.2:36429': {'host': {'python': '3.8.12.final.0',
    'python-bits': 64,
    'OS': 'Linux',
    'OS-release': '5.13.0-20-generic',
    'machine': 'x86_64',
    'processor': 'x86_64',
    'byteorder': 'little',
    'LC_ALL': 'C.UTF-8',
    'LANG': 'C.UTF-8'},
   'packages': {'python': '3.8.12.final.0',
    'dask': '2021.10.0',
    'distributed': '2021.10.0',
    'msgpack': '1.0.2',
    'cloudpickle': '2.0.0',
    'tornado': '6.1',
    'toolz': '0.11.1',
    'numpy': '1.20.3',
    'pandas': '1.3.0',
    'lz4': '3.1.3',
    'blosc': '1.10.2',
    'xgboost': '1.5.0'}},
  'tcp://172.17.0.5:44029': {'host': {'python': '3.8.12.final.0',
    'python-bits': 64,
    'OS': 'Linux',
    'OS-release': '5.13.0-20-generic',
    'machine': 'x86_64',
    'processor': 'x86_64',
    'byteorder': 'little',
    'LC_ALL': 'C.UTF-8',
    'LANG': 'C.UTF-8'},
   'packages': {'python': '3.8.12.final.0',
    'dask': '2021.10.0',
    'distributed': '2021.10.0',
    'msgpack': '1.0.2',
    'cloudpickle': '2.0.0',
    'tornado': '6.1',
    'toolz': '0.11.1',
    'numpy': '1.20.3',
    'pandas': '1.3.0',
    'lz4': '3.1.3',
    'blosc': '1.10.2',
    'xgboost': '1.5.0'}}},
 'client': {'host': {'python': '3.8.12.final.0',
   'python-bits': 64,
   'OS': 'Linux',
   'OS-release': '5.13.0-20-generic',
   'machine': 'x86_64',
   'processor': 'x86_64',
   'byteorder': 'little',
   'LC_ALL': 'en_US.UTF-8',
   'LANG': 'en_US.UTF-8'},
  'packages': {'python': '3.8.12.final.0',
   'dask': '2021.10.0',
   'distributed': '2021.10.0',
   'msgpack': '1.0.2',
   'cloudpickle': '2.0.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.20.3',
   'pandas': '1.3.0',
   'lz4': '3.1.3',
   'blosc': '1.10.2',
   'xgboost': '1.5.0'}}}
```

**Comment by danielhstahl** [comment]
Apparently the scheduler also needs xgboost.  It works if I use the following config:

```
worker:
  replicas: 2
  resources:
    limits:
      cpu: 2
      memory: 1G
    requests:
      cpu: 2
      memory: 1G
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: xgboost -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade
scheduler:
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: xgboost -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade
# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade
```
