### ISSUE TITLE
dask requires bokeh on conda-forge?

### ISSUE THREAD

**Issue by raphaelquast** [dask/dask#8838]
**What happened**:

I ported this issue I've raised on `datashader` (https://github.com/holoviz/datashader/issues/1053) to here since I think this is actually coming from `dask`...

It seems that `dask` has a dependency on the plotting-library `bokeh` when being installed via `conda-forge`
(and as far as I know this should not be a requirement for the functionalities that dask provides)

from the meta.yml of the feedstock:
```
requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8
    - dask-core {{ version }}
    - distributed {{ version }}
    - cytoolz >=0.8.2
    - numpy >=1.18
    - pandas >=1.0
    - bokeh >=2.4.2
    - jinja2
```

**What you expected to happen**:
well, I'd like to avoid installing bokeh if I don't intend to use it

**Minimal Complete Verifiable Example**:
running this on a fresh conda-environment 
```python
conda install -c conda-forge dask
```
adds the following dependency:
```
...
  + bokeh                                 2.4.2  py39hcbf5309_0      conda-forge/win-64      14 MB
...
```
