### ISSUE TITLE
Filters in read_parquet are not working in the latest dask version

### ISSUE THREAD

**Issue by SultanOrazbayev** [dask/dask#9246]
While trying to reproduce code from [this answer](https://stackoverflow.com/a/72892141/10693596) with different dask versions I ran into inconsistent behavior.

Consider this snippet:

```python
from dask.dataframe import read_parquet
from dask.datasets import timeseries

df = timeseries(end="2000-01-03", seed=0).reset_index()
df["date"] = df["timestamp"].dt.date.astype("str")
df.to_parquet("test.pqt", partition_on=["id", "date"])
rare_id = df["id"].value_counts().compute().tail(1).index.values[0]

ddf = read_parquet("test.pqt", filters=[[("id", "==", rare_id)]], engine="pyarrow")
print(ddf.npartitions)  # 1 when using environment 2 defined below, but 491 when using environment 1 (latest dask)
```

Environment 1:

```yaml
name: dask
channels:
- conda-forge
dependencies:
- python=3.10
- ipykernel=6.4.1
- dask=2022.6.1
- pyarrow=8.0.0
- fastparquet=0.8.1
- pandas=1.4.3
```

Environment 2:

```yaml
name: dask2
channels:
- conda-forge
dependencies:
- python=3.10
- ipykernel=6.4.1
- dask=2022.1.0
- pyarrow=8.0.0
- fastparquet=0.8.1
- pandas=1.4.3
```

Just in case, here's the output of the fancy new `.show_versions()`:

```python
import dask

dask.utils.show_versions()
# {
#   "Python": "3.10.5",
#   "Platform": "Darwin",
#   "dask": "2022.6.1",
#   "distributed": "2022.6.1",
#   "numpy": "1.23.0",
#   "pandas": "1.4.3",
#   "cloudpickle": "2.1.0",
#   "fsspec": "2022.5.0",
#   "bokeh": "2.4.3",
#   "fastparquet": "0.8.1",
#   "pyarrow": "8.0.0",
#   "zarr": null
# }
```
